[workspace]
channels = ["https://prefix.dev/brads-forge", "conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
init = "task init"

[tasks.code]
depends-on = ["init"]
cmd = "code ."

[target.unix.activation.env]
PATH = "$PWD/scripts:$PATH"

[dependencies]
cocogitto = ">=7.0.0,<8"
deno = ">=2.7.13,<2.8"
dprint = ">=0.54.0,<0.55"
lefthook = ">=2.1.6,<3"
opentofu = ">=1.11.6,<2"
task = ">=3.50.0,<4"
terraform = ">=1.14.9,<2"
gh = ">=2.91.0,<3"
go = ">=1.26.2,<2"
copilot-cli = ">=1.0.34,<2"
