# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: 3

dotenv: [".env"]
set: [pipefail]
shopt: [globstar]

tasks:
  init:
    desc: Setup dev env (anything that pixi can't install and setup for us).
    cmds:
      - lefthook install -f
      - git config pull.rebase true
      - git config core.editor "code --wait"
      - git config commit.template "$PWD/.gitmsgtpl"
      - "{{if .CI}}git config --global user.name github-actions[bot]{{end}}"
      - "{{if .CI}}git config --global user.email github-actions[bot]@users.noreply.github.com{{end}}"

  lint:
    desc: Lints our code to ensure it remains of a high quality.
    cmds:
      - dprint check

  fmt:
    desc: Formats our code to ensure it looks consistent.
    cmds:
      - dprint fmt
